# Generated by Django 3.2.4 on 2021-06-05 11:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('text', models.TextField()),
                ('meta', models.TextField(default='{}')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='annotator.project')),
            ],
            options={
                'verbose_name': 'Offerta',
                'verbose_name_plural': 'Offerte',
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('text', config='italian'), name='idx_offer_text_fullsearch'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['text'], name='idx_offer_text'),
        ),
    ]
